### ISSUE TITLE
API데이터 연동

### ISSUE THREAD

**Issue by annie309409** [annie309409/WAKAUT#22]
[경기도 공공체육시설](https://data.gg.go.kr/portal/data/service/selectServicePage.do?page=1&sortColumn=&sortDirection=&infId=6LMU5TBQ6RJJRBLAZWBC21105087&infSeq=1&searchWord=%EC%B2%B4%EC%9C%A1%EC%8B%9C%EC%84%A4) API 데이터 연동 및 [kakaomap](https://apis.map.kakao.com/web/) 연동 방법 찾아보기

**Comment by hideonbush3** [comment]
찾아보기 시작합니다.

**Comment by hideonbush3** [comment]
완료
